### PR TITLE
Enhanced .vscode folder configuration

### PR DESCRIPTION
**Pull request by ozzr**
Added capabilities to properly debug `dev` builds of the extension

### CODE REVIEW

**Comment by paddy-exe** [comment]
@ozzr Did you want to add the details for the changes as well in the README? This PR would also need a squash

**Comment by ozzr** [comment]
Lo siento, no he tenido tiempo, pero no lo he olvidado. 

Mi hijo está al nacer asi que tengo muchas cosas que dejar preparadas antes de eso.

Quizas puedas copiar y pegar lo que escribí cuando abrí la issue. Creo que aquello es sufieciente hasta que pueda yo sentarme en la PC

**Comment by ozzr** [comment]
Sorry, I haven't had time, but I haven't forgotten.

 My son is due to be born so I have many things to prepare before then.

 Maybe you can copy and paste what I wrote when I opened the issue.  I think that's enough until I can sit at the PC
Or maybe redirect from the main page to the issue itself

**Comment by paddy-exe** [comment]
Hey @ozzr first-off: Congratulations 🥳 🎉 and no worries about this. It can wait until you have more time again and can rewrite it with more details. :D I will copy your issue description and use that as a base.

**Comment by paddy-exe** [comment]
Thanks for the contribution!

**Pull request merged**
